<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \ContactUs\Form\ContactUsForm $form
 * @var string $heading
 * @var string $html Passed directly from the options.
 * @var bool $asButton Passed directly from the options.
 * @var ?\Common\Stdlib\PsrMessage $message Message of success or error to the user.
 * @var string $status "success" or "error"
 * @var string $contact "us" or "author"
 */

// Note: you may use css grid / flex to quick adapt the form and reorder fields.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
?>

<div class="contact-us-block">
    <?php if (!empty($heading)): ?>
    <h4><?= $escape($heading) ?></h4>
    <?php endif; ?>

    <?= $html ?? '' ?>

    <?php if ($message): ?>
    <p class="explanation <?= $status ?>"><?= $message ?></p>
    <?php endif; ?>
    <?php if ($status !== 'success' && $form): ?>
    <?= $this->form($form) ?>
    <?php endif; ?>
</div>
