<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var bool $isSelected
 * @var int $maxResources
 * @var array $selectedResourceIds
 * @var string $urlContactUsSelect
 * @var string $label
 *
 * And passed options.
 */

$plugins = $this->getHelperPluginManager();
$identity = $plugins->get('identity');
$assetUrl = $plugins->get('assetUrl');
$headLink = $plugins->get('headLink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$headScript = $plugins->get('headScript');

$user = $identity();

$headLink
    ->appendStylesheet($assetUrl('css/contact-us.css', 'ContactUs'));
$headScript
    ->appendFile($assetUrl('js/contact-us.js', 'ContactUs'), 'text/javascript', ['defer' => 'defer']);
?>

<input class="contact-us-resource contact-us-selection" type="checkbox" <?= $isSelected ? 'checked="checked" ' : '' ?>name="id[]" value="<?= $resource->id() ?>" title="<?= $escapeAttr($label) ?>" data-url="<?= $urlContactUsSelect ?>" data-local-storage="<?= $user ? '0' : '1' ?>" data-max-resources="<?= $maxResources ?>" data-message-fail=""/>
