<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var array $resourceIds
 * @var bool $isGuestActive
 * @var bool $isSession
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$api = $plugins->get('api');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$headLink = $plugins->get('headLink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$headScript = $plugins->get('headScript');
$translatePlural = $plugins->get('translatePlural');
$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;

$filterLocale = (bool) $siteSetting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;
$langValue = $filterLocale ? [$siteLang, ''] : null;
$untitled = $translate('[Untitled]');

$headingTerm = $siteSetting('browse_heading_property_term');
$bodyTerm = $siteSetting('browse_body_property_term');

$defaultThumbnailUrl = $assetUrl('thumbnails/default.png', 'Omeka', true);
$defaultThumbnailLabel = $translate('No media');
$defaultThumbnail = '<img src="' . $defaultThumbnailUrl . '" title="' . $defaultThumbnailLabel . '"/>';

if (!$isSession) {
    // For now, contact us is only possible with items and api resources is not available.
    /** @var \Omeka\Api\Representation\ItemRepresentation $resources */
    $resources = $resourceIds ? $api->search('items', ['id' => $resourceIds])->getContent() : [];
}

$this->htmlElement('body')->appendAttribute('class', 'item resource browse contact-us');

$headLink
    ->appendStylesheet($assetUrl('css/contact-us.css', 'ContactUs'));
$headScript
    ->appendFile($assetUrl('js/contact-us.js', 'ContactUs'), 'text/javascript', ['defer' => 'defer']);
?>

<?php if ($breadcrumbs): ?>
<?= $breadcrumbs() ?>
<?php endif; ?>

<?= $this->pageTitle($siteSetting('contactus_label_selection', $translate('Selection for contact')), 2) ?>

<?php $this->trigger('view.browse.before'); ?>

<?php if (!empty($resources)): ?>

<div class="browse-controls">
    <span class="row-count"><?= sprintf($translatePlural('%d resource', '%d resources', count($resourceIds)), count($resourceIds)) ?></span>
</div>

<ul class="resource-list">
    <?php
    foreach ($resources as $resource):
        $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $untitled, 'lang' => $langValue]) : $resource->displayTitle($untitled, $lang);
        $body = $bodyTerm ? $resource->value($bodyTerm, ['lang' => $langValue]) : $resource->displayDescription(null, $lang);
        $resourceType = $resource->getControllerName();
        $thumbnailResource = $thumbnail($resource, 'medium') ?: $defaultThumbnail;
        $linkContent = sprintf('%1$s<span class="resource-name">%2$s</span>', $thumbnailResource, $escape($heading));
        ?>
        <li class="resource <?= $resourceType ?>">
            <?= $resource->linkRaw($linkContent, null, ['class' => 'resource-link']) ?>
            <?php if ($body): ?>
            <div class="description"><?= $escape($body) ?></div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>

<?php elseif ($isSession): ?>

<div class="browse-controls contact-us-template hidden" style="display: none;" data-label-count-singular="<?= $translate('%d resource') ?>" data-label-count-plural="<?= $translate('%d resources') ?>">
    <span class="row-count">{total_resources}</span>
</div>

<ul class="resource-list contact-us-template hidden" style="display: none;" data-url-api="<?= $url('api/default', ['resource' => 'items']) ?>" data-url-base-item="<?= $url('site/resource', ['controller' => 'item'], true)?>" data-default-untitled="<?= $untitled ?>" data-default-thumbnail-url="<?= $escapeAttr($defaultThumbnailUrl) ?>" data-default-thumbnail-label="<?= $escapeAttr($defaultThumbnailLabel) ?>"/>
    <li class="resource item">
        <a class="resource-link" href="{resource_url}">
            <img src="{thumbnail_url}" title="{thumbnail_label}"/>
            <span class="resource-name">{resource_title}</span>
            <div class="description">{resource_description}</div>
        </a>
    </li>
</ul>

<p class="no-resource contact-us-template hidden" style="display: none;">
    <?= $translate('No resource is selected.') ?>
</p>

<?php else: ?>

<p class="no-resource">
    <?= $translate('No resource is selected.') ?>
</p>

<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>

<?php //= $this->contactUsButton() ?>

<div class="contact-us-tools">
    <button class="contact-us-button contact-us-write contact-us-fill-form">
        <span class="contact-us-write"><?= $escapeAttr($translate('Fill the form')) ?></span>
    </button>
</div>

<div class="contact-us-form hidden" style="display: none;">
    <?= $this->contactUs([
        'heading' => $translate('Complete the request'),
        'fields' => [
            'id' => [
                'value' => $resourceIds,
                'type' => 'hidden',
            ],
        ],
    ]) ?>
</div>
