<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \ContactUs\Api\Representation\MessageRepresentation[] $messages
 * @var \ContactUs\Api\Representation\MessageRepresentation[] $resources
 * @var \Omeka\Form\ConfirmForm $formDeleteSelected
 * @var \Omeka\Form\ConfirmForm $formDeleteAll
 */

use ContactUs\Api\Adapter\MessageAdapter;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$userIsAllowed = $plugins->get('userIsAllowed');

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-page-action-menu.css', 'Common'))
    ->appendStylesheet($assetUrl('css/contact-us-admin.css', 'ContactUs'));
$this->headScript()
    ->appendFile($assetUrl('js/contact-us-admin.js', 'ContactUs'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'contact-message contact-messages browse');

$sortHeadings = [
    [
        'label' => $translate('Sender name'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Sender email'),
        'value' => 'email',
    ],
    [
        'label' => $translate('Date sent'),
        'value' => 'created',
    ],
];

$batchEditRight = $userIsAllowed(MessageAdapter::class, 'batch-update')
    || $userIsAllowed(MessageAdapter::class, 'batch-delete');
$editRight = $userIsAllowed(MessageAdapter::class, 'update')
    || $userIsAllowed(MessageAdapter::class, 'delete');
?>

<?= $this->pageTitle('', 1, $translate('Contact messages')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <?php // echo $hyperlink($translate('Advanced search'), $url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']) ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<?php if ($messages): ?>
<div id="page-actions">
    <?php if ($userIsAllowed(MessageAdapter::class, 'batch-update')): ?>
    <div class="page-action-menu">
        <div class="with-sub-menu">
            <a href="#" class="button expand"
                aria-label="<?= $escapeAttr($translate('Expand')) ?>"
                title="<?= $escapeAttr($translate('Expand')) ?>"><?= $escape($translate('Actions')) ?></a>
            <ul class="collapsible">
                <li><a href="#"
                    class="batch-actions batch-property"
                    data-batch-property-url="<?= $escapeAttr($url('admin/contact-message/default', ['action' => 'batch-set-read'], true)) ?>"
                    data-property="is_read"
                    data-status="read"><?= $escape($translate('Set read')) ?></a></li>
                <li><a href="#"
                    class="batch-actions batch-property"
                    data-batch-property-url="<?= $escapeAttr($url('admin/contact-message/default', ['action' => 'batch-set-not-read'], true)) ?>"
                    data-property="is_read"
                    data-status="not-read"><?= $escape($translate('Set not read')) ?></a></li>
                <li><a href="#"
                    class="batch-actions batch-property"
                    data-batch-property-url="<?= $escapeAttr($url('admin/contact-message/default', ['action' => 'batch-set-spam'], true)) ?>"
                    data-property="is_spam"
                    data-status="spam"><?= $escape($translate('Set spam')) ?></a></li>
                <li><a href="#"
                    class="batch-actions batch-property"
                    data-batch-property-url="<?= $escapeAttr($url('admin/contact-message/default', ['action' => 'batch-set-not-spam'], true)) ?>"
                    data-property="is_spam"
                    data-status="not-spam"><?= $escape($translate('Set not spam')) ?></a></li>
            </ul>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($userIsAllowed(MessageAdapter::class, 'batch-delete')): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?= $escapeAttr($url('admin/contact-message/default', ['action' => 'batch-delete-confirm'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Delete')) ?>"
        title="<?= $escapeAttr($translate('Delete')) ?>"><?= $escape($translate('Delete')) ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($messages)): ?>
<div class="no-resources">
    <p><?= $translate('There are no messages.') ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<table class="tablesaw <?php if ($batchEditRight): echo 'batch-edit'; endif ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-tag">
                <?php if ($batchEditRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?= $translate('Message') ?>
            </th>
            <th><?= $translate('Sender') ?></th>
            <th><?= $translate('Date sent') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($messages as $message): ?>
        <?php
        $owner = $message->owner();
        ?>
        <tr class="contact-message">
            <td>
                <?php if ($batchEditRight): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?= $message->id() ?>">
                <?php endif; ?>
                <?php $subject = $message->subject() ?: $message->body() ?>
                <?= $escape(mb_substr($subject, 0, 200)) . (mb_strlen($subject) > 200 ? '…' : '') ?>
                <?php if ($message->isToAuthor()): ?>
                <span class="o-icon-user" aria-label="<?= $translate('Message to author') ?>"></span>
                <?php endif; ?>
                <ul class="actions">
                    <?php $editRightContactUs = $message->userIsAllowed('update'); ?>
                    <?php if ($editRightContactUs): ?>
                    <li><a href="#"
                        class="toggle-property is_read o-icon-<?= $message->isRead() ? 'read' : 'not-read' ?>"
                        data-toggle-url="<?= $escapeAttr($message->url('toggle-read')) ?>"
                        data-property="is_read"
                        data-status="<?= $message->isRead() ? 'read' : 'not-read' ?>"
                        aria-label="<?= $escapeAttr($translate('Toggle read')) ?>"
                        title="<?= $escapeAttr($translate('Toggle read')) ?>"></a></li>
                    <li><a href="#"
                        class="toggle-property is_spam o-icon-<?= $message->isSpam() ? 'spam' : 'not-spam' ?>"
                        data-toggle-url="<?= $escapeAttr($message->url('toggle-spam')) ?>"
                        data-property="is_spam"
                        data-status="<?= $message->isSpam() ? 'spam' : 'not-spam' ?>"
                        aria-label="<?= $escapeAttr($translate('Toggle spam')) ?>"
                        title="<?= $escapeAttr($translate('Toggle spam')) ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($editRightContactUs): ?>
                    <li><a href="#"
                        class="toggle-property has_zip o-icon-<?= $message->hasZip() ? 'zip' : 'no-zip' ?>"
                        data-toggle-url="<?= $escapeAttr($message->url('toggle-zip')) ?>"
                        data-property="has_zip"
                        data-status="<?= $message->hasZip() ? 'zip' : 'no-zip' ?>"
                        aria-label="<?= $escapeAttr($translate('Toggle zip')) ?>"
                        title="<?= $escapeAttr($translate('Toggle zip')) ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($message->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?= $escapeAttr($message->url('delete-confirm')) ?>"
                        aria-label="<?= $escapeAttr($translate('Delete')) ?>"
                        title="<?= $escapeAttr($translate('Delete')) ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?= $escapeAttr($message->url('show-details')) ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?= $escapeAttr($translate('Details')) ?>"
                        title="<?= $escapeAttr($translate('Details')) ?>"></a></li>
                </ul>
            </td>
            <td>
                <?php if ($owner): ?>
                <span class="message-email"><?= $hyperlink($owner->name(), $url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])) ?></span>
                <?php else: ?>
                <span class="message-email message-public"><?= $hyperlink($message->name() ?: $message->email(), 'mailto:' . $message->email()) ?></span>
                <span class="o-icon-users" aria-label="<?= $translate('Public') ?>"></span>
                <?php endif; ?>
            </td>
            <td><?= $escape($i18n->dateFormat($message->created(), 'medium', 'medium')) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after') ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escapeAttr($translate('Close')) ?>"
        title="<?= $escapeAttr($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
