<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \ContactUs\Api\Representation\MessageRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$fields = $resource->fields() ?: [];
$site = $resource->site();
?>

<?php $message = $resource; ?>
<div class="resource-details" data-resource-values="<?php // echo $escape($values) ?>">
    <h3 class="o-module-contact"><?= $message->link(sprintf($translate('message #%d'), $message->id())) ?></h3>
    <div class="meta-group">
        <?php $owner = $message->owner(); ?>
        <h4><?= $escape($translate('Sender')) ?> <?php if (!$owner): ?><span class="contact-message-public"><?= $translate('(public)') ?></span><?php endif; ?></h4>
        <div class="value">
            <?php if ($owner): ?>
            <span class="contact-message-email"><?= $hyperlink($owner->name(), $url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])) ?></span>
            <?php else: ?>
            <span class="contact-message-email message-public"><?= $hyperlink($message->email(), 'mailto:' . $message->email()) ?></span>
            <span class="contact-message-name"><?= $message->name() ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="meta-group">
        <?php $attachedResource = $message->resource(); ?>
        <?php $attachedResourceIds = $message->resourceIds(); ?>
        <?php if ($attachedResource): ?>
        <?php $attachedResourceName = $attachedResource->getControllerName(); ?>
        <h4><?= $escape($translate(ucfirst($attachedResourceName))) ?> <span class="fa resource-name <?= $attachedResourceName ?>" aria-label="<?= $attachedResourceName ?>"></span></h4>
        <div class="value">
            <span class="resource-name"><?= $attachedResource->link($attachedResource->displayTitle()) ?></span>
            <?php if (!$attachedResource->isPublic()): ?>
            <span class="o-icon-private" aria-label="<?= $translate('Private') ?>"></span>
            <?php endif; ?>
        </div>
        <div class="value">
            <a href="<?= $message->zipUrl() ?>" download="download" target="_self"><?= $translate('Link to the zipped file when created') ?></a>
        </div>
        <?php elseif ($attachedResourceIds): ?>
        <h4><?= $escape($translate('Multiple resources')) ?></h4>
        <div class="value">
            <a class="resource-name" href="<?= $escapeAttr($url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['id' => $attachedResourceIds]])) ?>"><?= sprintf($translate('%d items (admin)'), count($attachedResourceIds)) ?></a>
            <?php if ($site): ?>
            <div>
                <a class="resource-name" href="<?= $escapeAttr($url('site/resource', ['controller' => 'item', 'action' => 'browse', 'site-slug' => $site->slug()], ['query' => ['id' => $attachedResourceIds]])) ?>"><?= sprintf($translate('%d items (public)'), count($attachedResourceIds)) ?></a>
            </div>
            <?php endif; ?>
        </div>
        <div class="value">
            <a href="<?= $message->zipUrl() ?>" download="download" target="_self"><?= $translate('Link to the zipped files when created') ?></a>
        </div>
        <?php else: ?>
        <h4><?= $escape($translate('Attached resources')) ?></h4>
        <div class="value">
            <span><?= $escape($translate('None')) ?></span>
        </div>
        <?php endif; ?>
    </div>
    <div class="meta-group">
        <?php if ($site): ?>
        <h4><?= $escape($translate('Site')) ?></h4>
        <div class="value">
            <span class="site-name"><?= $site->link($site->title()) ?></span>
            <?php if (!$site->isPublic()): ?>
            <span class="o-icon-private" aria-label="<?= $translate('Private') ?>"></span>
            <?php endif; ?>
        </div>
        <?php endif; ?>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Date Created') ?></h4>
        <div class="value"><?= $escape($i18n->dateFormat($message->created(), 'medium', 'medium')) ?></div>
        <?php if ($modified = $message->modified()): ?>
        <h4><?= $translate('Last modified') ?></h4>
        <div class="value"><?= $escape($i18n->dateFormat($modified, 'medium', 'medium')) ?></div>
        <?php endif; ?>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Infos') ?></h4>
        <div class="value">
            <div class="to-author"><?= $message->isToAuthor() ? $translate('Message to author') : $translate('Message to us') ?></div>
            <div class="is-read"><?= sprintf($translate('Is read: %s'), $message->isRead() ? $translate('yes') : $translate('no')) ?></div>
            <div class="is-spam"><?= sprintf($translate('Is spam: %s'), $message->isSpam() ? $translate('yes') : $translate('no')) ?></div>
            <div class="has-zip"><?= sprintf($translate('Has zip: %s'), $message->hasZip() ? $translate('yes') : $translate('no')) ?></div>
        </div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Subject') ?></h4>
        <div class="value"><?= $escape($message->subject() ?: $translate('[No subject]')) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Body') ?></h4>
        <div class="value"><?= $escape($message->body()) ?></div>
    </div>
    <?php foreach ($fields as $key => $value):
        if ($key === 'id') continue; ?>
    <div class="meta-group">
        <h4><?= $key ?></h4>
        <?php foreach (is_array($value) ? $value : [$value] as $val): ?>
        <div class="value"><?= $escape($val) ?></div>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
    <?php if ($fileUrl = $message->assetUrl()): ?>
    <div class="meta-group">
        <h4><?= $translate('Attached file') ?></h4>
        <div class="value">
            <?= sprintf($translate('Media type: %s'), $message->mediaType()) ?>
        </div>
        <div class="value">
            <?= $hyperlink($message->source() ?: $fileUrl, $fileUrl) ?>
            <?php if (!$owner): ?>
            <span><?= $translate('Warning: content from an anonymous user') ?></span>
            <?php elseif ($owner->role() === 'guest'): ?>
            <span><?= $translate('Warning: content from a guest user') ?></span>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
    <?php $newsletter = $message->newsletter() ?>
    <?php if (is_bool($newsletter)): ?>
    <div class="meta-group">
        <h4><?= $translate('Newsletter') ?></h4>
        <div class="value"><?= $newsletter ? $translate('yes') : $translate('no') ?></div>
    </div>
    <?php endif; ?>
</div>
