<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \ContactUs\Form\ContactUsForm $form
 * @var string $message
 * @var string $status
 */

?>
<div class="contact-us-block">
    <?php if ($message): ?>
    <p class="explanation <?= $status ?>"><?= $message ?></p>
    <?php endif; ?>
    <?php if ($form): ?>
    <?php echo $this->form($form); ?>
    <?php endif; ?>
</div>
