<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \ContactUs\Form\ContactUsForm $form
 * @var string $heading
 * @var string $html
 * @var string $message
 * @var string $status "success" or "error"
 */

$escape = $this->plugin('escapeHtml');

$style = '
.contact-us-block .error {
    color: red;
}
';
$this->headStyle()->appendStyle($style);
?>

<div class="contact-us-block">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <?= $html ?>

    <?php if ($message): ?>
    <p class="explanation <?= $status ?>"><?= $message ?></p>
    <?php endif; ?>
    <?php if ($form): ?>
    <?= $this->form($form) ?>
    <?php endif; ?>
</div>
