<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \ContactUs\Form\ContactUsForm $form
 * @var string $heading
 * @var string $message
 * @var string $status "success" or "error"
 * @var array $options
 */

$escape = $this->plugin('escapeHtml');

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/contact-us.css', 'ContactUs'));
?>

<div class="contact-us-block">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <?php if ($message): ?>
    <p class="explanation <?= $status ?>"><?= $message ?></p>
    <?php endif; ?>
    <?php if ($form): ?>
    <?= $this->form($form) ?>
    <?php endif; ?>
</div>
