<?php
// @deprecated. Use common/contact-us.phtml

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \ContactUs\Form\ContactUsForm $form
 * @var string $heading
 * @var string $html Passed directly from the options.
 * @var string $message
 * @var string $status "success" or "error"
 */

echo $this->partial('common/contact-us');
